### ISSUE TITLE
Persisting into Cassandra second time

### ISSUE THREAD

**Issue by utkarshdeep** [oscerd/camel-cassandra#2]
I wrote a camel route to poll files from FTP server and then persisting an entity into cassandra. It worked fine the first time the route got executed, but when the route got invoked the second time, it throws some error. Below I am appending the code and the error:
**CODE**
`PropertiesComponent pc = getContext().getComponent("properties", PropertiesComponent.class);
pc.setLocation("classpath:ftp.properties");`

`HashMap<String, Object> insert = new HashMap<String, Object>();
insert.put("id", UUID.randomUUID());
insert.put("name", "utkarsh0");`

`String cassandraAddress = "127.0.0.1";
List<String> collAddr = new ArrayList<String>();
collAddr.add(cassandraAddress);
getContext().getShutdownStrategy().setTimeout(10);`

`from("{{ftp.server}}")
.to("file:target/download")
.log("Downloaded file ${file:name} complete.")
.setHeader(CassandraConstants.CASSANDRA_CONTACT_POINTS, constant(collAddr))
.setBody(constant(""))
.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, constant(insert))
.to("cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert")
.removeHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT);`

**ERROR**
`2018-01-16 00:21:44,052 [alhost:21/files] ERROR DefaultErrorHandler - Failed delivery for (MessageId: ID-utkarsh-1516042220798-0-5 on ExchangeId: ID-utkarsh-1516042220798-0-4). Exhausted after delivery attempt: 1 caught: com.github.oscerd.component.cassandra.CassandraException: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)`
Message History

RouteId ProcessorId Processor Elapsed (ms)
[route1 ] [route1 ] [ftp://localhost:21/files?delay=5s&move=done&password=xxxxxx&username=sammy ] [ 2316]
[route1 ] [to1 ] [file:target/download ] [ 1]
[route1 ] [log1 ] [log ] [ 0]
[route1 ] [setHeader1 ] [setHeader[CamelCassandraContactPoints] ] [ 1]
[route1 ] [setBody1 ] [setBody[constant{}] ] [ 0]
[route1 ] [setHeader2 ] [setHeader[CamelCassandraInsertObject] ] [ 0]
[route1 ] [to2 ] [cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert ] [ 2312]
**Stacktrace**

com.github.oscerd.component.cassandra.CassandraException: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
at com.github.oscerd.component.cassandra.CassandraComponent.wrapInCamelCassandraException(CassandraComponent.java:50) ~[camel-cassandra-2.17.0.jar:?]
at com.github.oscerd.component.cassandra.CassandraProducer.process(CassandraProducer.java:111) ~[camel-cassandra-2.17.0.jar:?]
at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.SendProcessor$2.doInAsyncProducer(SendProcessor.java:178) ~[camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445) ~[camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:173) ~[camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:176) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:452) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.component.file.remote.RemoteFileConsumer.processExchange(RemoteFileConsumer.java:137) [camel-ftp-2.20.1.jar:2.20.1]
at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:219) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:183) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.20.1.jar:2.20.1]
at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.20.1.jar:2.20.1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63) ~[cassandra-driver-core-3.0.0.jar:?]
at com.github.oscerd.component.cassandra.CassandraProducer.doInsert(CassandraProducer.java:351) ~[camel-cassandra-2.17.0.jar:?]
at com.github.oscerd.component.cassandra.CassandraProducer.invokeOperation(CassandraProducer.java:150) ~[camel-cassandra-2.17.0.jar:?]
at com.github.oscerd.component.cassandra.CassandraProducer.process(CassandraProducer.java:109) ~[camel-cassandra-2.17.0.jar:?]
... 24 more
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
at com.datastax.driver.core.Responses$Error.asException(Responses.java:132) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005) ~[cassandra-driver-core-3.0.0.jar:?]
at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928) ~[cassandra-driver-core-3.0.0.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[netty-handler-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.33.Final.jar:4.0.33.Final]
... 1 more
2018-01-16 00:21:44,071 [alhost:21/files] WARN GenericFileOnCompletion - Rollback file strategy: org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@51d5efde for file: RemoteFile[t5.txt]

**Comment by oscerd** [comment]
What file is polled the second time? What are the content of this file? Can you provide a reproducer?

**Comment by utkarshdeep** [comment]
A simple text file is polled the second time, just like the first time.
The content of the file is a simple String text line.
Reproducer? Can you elaborate on that?

**Comment by oscerd** [comment]
I mean can you post the content of first and second file and the schema of the Cassandra table

**Comment by utkarshdeep** [comment]
First file - "Hi this is the file first in FTP."
Second file - "Hi this is the second file in FTP"
Cassandra table create statement - `CREATE TABLE test ( id UUID PRIMARY KEY, name text)`

**Comment by oscerd** [comment]
Are you sure the code is right? You define insert at the beginning and then you are using always the same insert object in the route. As far as I can tell, you are not writing the content of the files you are polling.

**Comment by utkarshdeep** [comment]
Well, the end goal is to write the content of the file into the database but for starters, I was trying to insert a simple object into the database. And as far as persisting the same object in DB is concerned I tried this below code as well but resulted in the same error. 
`HashMap<String, Object> insert = new HashMap<String, Object>();`
`insert.put("id", UUID.randomUUID());
insert.put("name", UUID.randomUUID().toString());`

**Comment by utkarshdeep** [comment]
[cqlsh 5.0.1 | Cassandra 3.11.1 | CQL spec 3.4.4 | Native protocol v4]

**Comment by oscerd** [comment]
ok, I'll take a look.

**Comment by utkarshdeep** [comment]
Thanks.

**Comment by oscerd** [comment]
This has been fixed.

**Comment by utkarshdeep** [comment]
Aside can you help me with code to convert the content of the file to Java objects or HashMap object so that I can persist it to Cassandra?

**Comment by oscerd** [comment]
You can write a processor that transform what you get from a file in an hashmap. You can do this with a processor or by writing a Camel TypeConverter (from a File to an Hashmap)

**Comment by utkarshdeep** [comment]
Thanks for the fix but actually now when the route gets invoked the file from FTP is able to move to the local file system but the data doesn't get persisted after the first time.
Could you be kind enough to show me the processor or Camel TypeConverter with an example?

**Comment by oscerd** [comment]
The fix doesn't work or do you get an exception?

**Comment by utkarshdeep** [comment]
I am not getting any exceptions but not able to persist the data after the first invocation of the camel route.
`from("{{ftp.server}}")`
                `.to("file:target/download")`
                `.log("Downloaded file ${file:name} complete.")`
                `.setHeader(CassandraConstants.CASSANDRA_CONTACT_POINTS, constant(collAddr))`
                `.setBody(constant(""))`
                `.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, constant(insert))`
                `.to("cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert")`
                `.removeHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT);`
By looking at the code can you think of any reason why this should be happening after the first successful run?

**Comment by oscerd** [comment]
Are you using camel-cassandra 2.20.2-SNAPSHOT ?

**Comment by utkarshdeep** [comment]
Yes, camel-cassandra-2.20.2-SNAPSHOT.jar by packaging it using maven.

**Comment by oscerd** [comment]
What is inside the insert object?

**Comment by utkarshdeep** [comment]
"Insert" object is just a HashMap<String, Object> object.

**Comment by oscerd** [comment]
If you create the insert object at the beginning and then you set it each time the route is invoked the insert will be always of the same entry, so you'll get exactly one entry in your table, always the same.

**Comment by oscerd** [comment]
I'll try to reproduce by the way

**Comment by oscerd** [comment]
You can try this by running a route like this one:

```java
public class CassandraRouteBuilder extends RouteBuilder {

	@Override
	public void configure() throws Exception {
    	String addr = "127.0.0.1";
    	List<String> collAddr = new ArrayList<String>();
    	collAddr.add(addr);
    	final HashMap<String, Object> insert = new HashMap<String, Object>();
    	from ("timer://timer?fixedRate=true&period=10000&repeatCount=5")
    	.setHeader(CassandraConstants.CASSANDRA_CONTACT_POINTS, constant(collAddr))
    	.setBody(constant(""))
    	.process(new Processor() {
			
			@Override
			public void process(Exchange exchange) throws Exception {
		    	insert.put("id", UUID.randomUUID()); 
		    	insert.put("name", UUID.randomUUID().toString());
			}
		})
    	.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, constant(insert))
    	.to("cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert")
    	.removeHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT);
	}
}
```

If you define the insert outside of the route, it will be always the same, obviously.

**Comment by utkarshdeep** [comment]
Actually, just to make sure that the same data is not created everything the route is invoked, I created a method that returns a new HashMap object which is called inside the constant method.
`.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, constant(newData()))`
where the method newData() is -
`public HashMap<String, Object> newData() {`
        `HashMap<String, Object> insert = new HashMap<String, Object>();`
        `insert.put("id", UUID.randomUUID());`
        `insert.put("name", UUID.randomUUID().toString());`
        `return insert;`
`}`

I guess now when everytime the route is invoked it creates a new object, you think it will create the same object now also?

**Comment by oscerd** [comment]
It should insert each time a different object in this way. Let me check.

**Comment by oscerd** [comment]
No, my fault. Since you create the method outside of the RouteBuilder, the newData method will be the same each time.

**Comment by oscerd** [comment]
Use a bean instead.

**Comment by oscerd** [comment]
For example

```java
    	String addr = "127.0.0.1";
    	List<String> collAddr = new ArrayList<String>();
    	collAddr.add(addr);
    	final HashMap<String, Object> insert = new HashMap<String, Object>();
    	from ("timer://timer?fixedRate=true&period=10000&repeatCount=5")
    	.setHeader(CassandraConstants.CASSANDRA_CONTACT_POINTS, constant(collAddr))
    	.setBody(constant(""))
    	.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, method(new BeanExample(), "newData"))
    	.to("cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert")
    	.removeHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT);
```
where BeanExample is

```java
public class BeanExample {

	public HashMap<String, Object> newData() {
		HashMap<String, Object> insert = new HashMap<String, Object>();
		insert.put("id", UUID.randomUUID());
		insert.put("name", UUID.randomUUID().toString());
		return insert;
		}
}
```

**Comment by utkarshdeep** [comment]
Actually, the code example you showed using the processor is working fine. My blunder that I was always creating the same object. Now I am able to insert new object every time there is a new file in FTP server. How do I process the file that was just picked by route from FTP? Can you help me there?
Anyways thanks for all the help man. You saved my day 👍

**Comment by oscerd** [comment]
If you have a file coming from the FTP, you can simply take the content as string by using the type converters provided by Camel

String text = exchange.getIn().getBody(String.class)

then use this string as part of your insert header.

**Comment by oscerd** [comment]
Did it work for you?

**Comment by utkarshdeep** [comment]
Yes, it did. Thanks, man. I have some questions to ask you regarding camel, I will connect with you on mail, ok?

**Comment by oscerd** [comment]
Sure.
