### ISSUE TITLE
Getting issue while inserting date

### ISSUE THREAD

**Issue by vinaykumarposina** [oscerd/camel-cassandra#26]
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Expected 8 or 0 byte long for date (24)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181) ~[cassandra-driver-core-3.7.2.jar:?]
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:215) ~[cassandra-driver-core-3.7.2.jar:?]

when i debug query is prepared like this in CassandraProducer
column:- recording_date 
type:- timestamp

`INSERT INTO heatmap_results (id,event_type,event_source,day,hr,minute,second,year,month,x,y,date_of_month,recording_date) VALUES (1590733711490,'4','undefined','Wednesday',1,39,4,2020,3,0,0,1,'2020-03-31T20:09:04.618Z')
`

Same query working in cli, but not from code.
-----------------------------
Update:-
session.execute(insert) -> session.execute(insert.toString()) --- it's working.

**Comment by oscerd** [comment]
What version are you using?

**Comment by vinaykumarposina** [comment]
> What version are you using?

3.0.0
